controllers:
   resource: ../src/Controller/
   type: annotation
   prefix: /{_locale}
   requirements:
       _locale: fr|en

redirect_to_homepage: 
    # redirection to /{_locale}/ when url is only /
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'App_index'
